BASIC:
  LOG_FLAG: True
DATA:
  SOURCES:
    - 1
    - 2
    - 3
  TARGET: 4
  TIME_WINDOW: 10
  SPLIT_RATIO: [ 0.7, 0.2 ]
TRAINING:
  EPOCHS: 100
  PIPELINE: ''
TESTING:
  BATCH_SIZE: 256
  PIPELINE:
    - 'arm'
MODEL:
  NAME: 'ResNet'
  ARM: 'ARM_LL'
  CKPT_SUFFIX: 'arm-ll'
