BASIC:
  LOG_FLAG: True
DATA:
  SOURCE: 1
  TARGET: 2
  TIME_WINDOW: 10
  DIM: 3
TRAINING:
  EPOCHS: 100
  LABEL_SMOOTHING: 0.2
  PIPELINE: 'default'
TESTING:
  BATCH_SIZE: 128
  PIPELINE:
    - 'delta'
MODEL:
  NAME: 'ResNet'
  CKPT_SUFFIX: 'resnet'