BASIC:
  LOG_FLAG: True
DATA:
  SOURCE: 1
  TARGET: 2
  TIME_WINDOW: 10
  DIM: 3
TRAINING:
  EPOCHS: 100
  PIPELINE: 'default'
TESTING:
  BATCH_SIZE: 128
  PIPELINE:
    - 'delta'
MODEL:
  NAME: 'ConvFormer'
  CKPT_SUFFIX: ''

norm_type: 'rn'
optim_type: 'adam'
loss_type: 'entropy'
ent_w: False
dot: 0.95
old_prior: 0.95
optim_lr: 0.00025
optim_momentum: 0.9
optim_wd: 0.
class_num: 10