BASIC:
  LOG_FLAG: False
  SOURCE: 1
  TARGET: 3
  SPLIT_RATIO: [0.7, 0.2]
MODEL:
  CKPT_SUFFIX: ''
TRAINING:
  PIPELINE: ''
TESTING:
  BATCH_SIZE: 256
  PIPELINE:
    - 'default'
    - 'norm'
    - 'tent'
