BASIC:
  LOG_FLAG: False
DATA:
  SOURCE: 1
  TARGET: 2
  SPLIT_RATIO: [ 0.7, 0.2 ]
  DIM: 3
  TIME_WINDOW: 100
MODEL:
  CKPT_SUFFIX: 'conv-former'
TRAINING:
  PIPELINE: ''
TESTING:
  BATCH_SIZE: 128
  PIPELINE:
    - 'default'
    - 'norm'
#    - 'tent'
