BASIC:
  CUDA_ID: 1
  LOG_FLAG: False
DATA:
  SOURCE: 1
  TARGET: 3
  SPLIT_RATIO: [ 0.7, 0.2 ]
  TIME_WINDOW: 36
  DIM: 4
MODEL:
  NAME: 'ResNet'
  CKPT_SUFFIX: 'resnet_1'
TRAINING:
  BATCH_SIZE: 128
  PIPELINE: ''
  LABEL_SMOOTHING: 0.0
TESTING:
  BATCH_SIZE: 128
  USE_ENTROPY: True
  WEIGHTING: False
  PIPELINE:
    - 'default'
    - 'norm'
    - 'tent'
    - 'delta'
    - 'divtent'
