train:
  epochs: 50
  batch_size: 128
  label_smoothing: 0.0
  pipeline: 'default'

  # early stopping tool setting
  patience: 5
  delta: 0
test:
  batch_size: 128
  pipeline:
    - 'default'
    - 'norm'
    - 'tent'
    - 'delta'
    - 'division'